### ISSUE TITLE
fix(ui-web): build.py needs Python 3.10+ for one keyword, so the documented from-source build fails on a stock macOS python3

### ISSUE THREAD

**Issue by Handsome-wzw** [EverMind-AI/Raven#526]
## Summary

`ui-web/build.py` writes the assembled page with `Path.write_text(out, encoding="utf-8", newline="")`. The `newline` keyword on `write_text` exists only from Python 3.10, and the script is otherwise plain standard-library code that compiles on 3.9. Every documented way of running it that does not go through `uv` -- `make build-ui` (`Makefile`, the `build-ui` target runs `python3 ui-web/build.py`), the `python3 ui-web/build.py` lines in `.github/workflows/ci.yml`, the usage line in the script's own docstring, and the self-hosting page's "from source" recipe (`make install-deps && make build-ui && uv run raven web`) -- picks up whatever `python3` is first on `PATH`. On a stock macOS that is Python 3.9.6, and the build dies after Vite has already succeeded.

`install.sh` and `install.ps1` are not affected: both run the script through `uv run --no-project python`, which is the project's 3.12.

## Steps to reproduce

1. On macOS with no other `python3` ahead of `/usr/bin/python3` (3.9.6), clone the repo and install Node and uv as the self-hosting page says.
2. `make install-deps && make build-ui`

## Expected behavior

`build-ui` assembles `ui-web/dist/index.html`. Either the script runs on any Python 3 (it uses nothing else that is version-specific), or the Makefile runs it on the interpreter the project already requires.

## Actual behavior

```
  File "ui-web/build.py", line 198, in main
    (dist / "index.html").write_text(out, encoding="utf-8", newline="")
TypeError: write_text() got an unexpected keyword argument 'newline'
```

The `newline=""` was added deliberately: a text write translates `\n` to `os.linesep`, which on Windows emits a CRLF page whose `<script>` payloads `check-page.mjs` can no longer extract. That intent is right; the keyword is just the one way to express it that ties the script to 3.10+.

Two remedies, both small; the first is the one that removes the dependency, the second only picks the right interpreter for one caller:

- **`ui-web/build.py`** (under the current `ui-web/` freeze, so filed rather than opened as a PR): write bytes instead of text, which has no newline translation on any platform and no version floor:

  ```python
  (dist / "index.html").write_bytes(out.encode("utf-8"))
  ```

  Measured on this branch: the page built by Python 3.9.6 and by 3.12 with this line have the same sha256, and it equals the sha256 of the page built by the current `write_text(newline="")` on 3.12; `check-page.mjs` passes on the result and the file holds zero CR bytes. The comment above the line should say why bytes: the script is run by whatever `python3` the caller has.

- **`Makefile`** `build-ui`: `uv run --frozen --python $(PYTHON_VERSION) python ui-web/build.py`, so the documented `make` path uses the project's interpreter like `install.sh` already does. This half does not touch `ui-web/` and can go now.

The self-hosting page's prerequisites do say Python 3.12, but `make build-ui` does not use it, which is what makes the recipe fail on a machine that satisfies the prerequisites.

## Environment

- Raven `main` at 04eb8a31 (2026-09-20)
- macOS 15, Apple Silicon; `/usr/bin/python3` = 3.9.6; repo venv Python 3.12

## Logs or screenshots

The traceback above is the whole output after `npm run build` succeeded.
